#!/bin/sh
set -e

CONF_LOGDIR="../conf/LOGDIR"
CONF_LOGUSER="../conf/LOGUSER"

SERVICE_NAME="$(basename $(cd ..; pwd))"

if [ -e "$CONF_LOGDIR" ]; then
    LOGDIR="$(cat $CONF_LOGDIR)"
else
    LOGDIR="/var/log/${SERVICE_NAME}"
fi

if [ -e "$CONF_LOGUSER" ]; then
    LOGUSER="$(cat $CONF_LOGUSER)"
else
    LOGUSER="${SERVICE_NAME}log"
fi

if [ ! -d "$LOGDIR" ]; then
    mkdir -p -m2750 "$LOGDIR" && chown "$LOGUSER":adm "$LOGDIR"
fi
exec chpst -u "$LOGUSER" svlogd -tt -v "$LOGDIR"
